### ISSUE TITLE
Mlst for E.coli?

### ISSUE THREAD

**Issue by galstriker** [iferres/MLSTar#15]
Hi @iferres 
I am a beginner in genome analysis.Mlstar is a fantastic software to do in silicon mlst and I love the plot function. When I going to do mlst for my E.coli samples, I listed all the profile, but couldn't find the profile for E.coli. So I wonder whether it support mlst for ecoli or not. Thank you.

**Comment by iferres** [comment]
Hi @galstriker, thanks to giving a try to MLSTar. 

Yes, E coli is not hosted by the BIGSdb, as mentioned in the [paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6192448/): "In 2016, the databases hosted on mlst.net were migrated to PubMLST, with the result that most MLST schemes are now hosted using the same platform (the major exceptions being Salmonella and Escherichia coli, hosted on Enterobase, although these schemes are mirrored on PubMLST)"; so it's not accessible from the rest api. I've checked and Salmonella was added since the publication, may be they'll host E coli in the future, I don't know.

A solution would be to manually download the profile and sequences from the Enterobase database (I think you can access from PubMLST) and then to pass the files to  `schemeFastas` and `schemeProfile` arguments. That should work if formats are compatible to those managed by the BIGSdb.

Let me know if you have any other question. Good luck!
