### ISSUE TITLE
cant find klebsiella pneumoniae in listPubmlst_orgs()

### ISSUE THREAD

**Issue by muntajihad** [iferres/MLSTar#17]
Hi,
I couldnt find "klebsiella pneumoniae" among orgs in listPubmlst() ?
thank you

**Comment by iferres** [comment]
Hi @muntajihad , the K pneumoniae MLST scheme is not hosted by PubMLST. That's why you are not finding it. You could download the files manually and pass them to the `schemeFastas` and `schemeProfile` arguments (`doMLST()` function). See the documentation `?doMLST`.

Reference: https://pubmlst.org/mlst
