### ISSUE TITLE
MLSTar further details

### ISSUE THREAD

**Issue by JFsanchezherrero** [iferres/MLSTar#5]
Dear developers,
I would be interested in implementing MLSTar within a pipeline for the identification/genotyping of bacterial isolates from clinical samples and I have a couple of questions and I wonder if you could answer them to me. 

1. Where can I find further information for possible options/arguments to pass to the different functions such as doMLST, etc. I havent found a manual or a description for them.

2. I would be interested in downloading the pubmlst profile at the beginning for a given bacteria and  populate my own profile and include samples that we had previously identified in order to asses relations between different isolates obtained and the database ones. I was wondering if there is a possibility to do this somehow or should I work it out.

Thank you very much in advance
Jose F. Sanchez

**Comment by iferres** [comment]
Hi @JFsanchezherrero , thanks for using MLSTar.

1. All functions are documented. Try `?MLSTar::doMLST` or `help(MLSTar::doMLST)` to display the manuals. That being said, I suggest you to reinstall the package prior to looking at the manuals because I have just updated some lines of it.

2. Interesting. So you want a way to update a local mlst database with new organisms. I think it is possible, but would require to tune the package as it is. I suggest to implement it separately. As you will see in the documentation (I think in the README vignette is well illustrated), the returned object has 2 `data.frames` with information about the scheme used and the alleles found. You can use this information to implement something like what you are saying.

**Comment by JFsanchezherrero** [comment]
Hi @iferres,

Thank you very much.

In fact, I found it myself a couple of minutes after sending the email...I guess I was excited about the discrovery of MLSTar and how to include it in my pipeline....I would update and check the new lines, for sure.

About the pipeline, once I have seen the documentation, I have seen how to do it and I guess I could update the profile with the new sample identified, update fasta files with new sequences (if any), re-generate blastdb(s) if any changed. 

I have tried the sample you provide for leptospira (By the way, number is changed is not 47 any more, is 48) and it worked really fast and smooth.

> listPubmlst_orgs()[47]
[1] "lsalivarius"
> listPubmlst_orgs()[48]
[1] "leptospira"

I then downloaded a reference genome for Staphylococcus aureus from NCBI, and using the same code you provide for leptospira it is taken ages to produce the plot even with the scheme_1 that only includes 7 MLST genes.

Do you know why it could be? Should I use only CDS sequences instead of whole genome?

Thanks!

**Comment by iferres** [comment]
Oh, that's probably because R is trying to compute and plot the whole profile of S. aureus, which may be **huge** considering it is a very studied organism. This kind of computation doesn't scale very well with the number of nodes (genomes). May be you should consider plotting only the result profile (`plot(x, what = "result")`), and not the whole mlst profile. It doesn't has any to do with the kind of input (genome vs cds), it's more a complexity issue.
